# Generated by Django 4.0.1 on 2022-01-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('other', 'Разное'), ('fruits', 'Фрукты'), ('vegetables', 'Овощи'), ('beverage', 'Напитки'), ('bakery', 'Выпечка')], default='other', max_length=15, verbose_name='Категория')),
                ('residue', models.IntegerField(verbose_name='Остаток')),
                ('price', models.FloatField(max_length=7, verbose_name='Цена')),
            ],
        ),
    ]
