# Generated by Django 4.0.1 on 2022-02-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productbasket_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='productbasket',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_product', to='store.order', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='productbasket',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_order', to='store.products', verbose_name='Продукт'),
        ),
    ]
