# Generated by Django 4.0.1 on 2022-02-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_order_product_alter_productbasket_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbasket',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Колличество'),
        ),
    ]
